cat > .github/workflows/auto-label.yml << 'EOF'
name: Auto-label Hacktoberfest PRs
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Hacktoberfest Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: hacktoberfest-accepted
EOF
